### ISSUE TITLE
Could not initialize time (err -19)

### ISSUE THREAD

**Issue by anngocnguyen** [e-ale/meta-pocketbeagle#6]
Hello,
I am trying to build pocketbeagle image with Yocto project and meta-pocketbeagle layer.
I checkout Yocto on Master branch and meta-pocketbeagle on master branch, too.
I have added pocketbeagle layer into bblayers. The bitbake build is OK.
However, when I put image on SD card for boot. I got the err message: "Could not initialize time (err -19)"
It looks like the err happens on u-boot. Please advise on how to fix it.

**Comment by twoerner** [comment]
This error is from U-Boot.

It appears as though U-Boot v2021.01 was the last release of upstream U-Boot that successfully boots the PocketBeagle. By the time U-Boot v2021.04 came out, it no longer works.

This means the last release to support the PocketBeagle is hardknott. Anything after that fails with the error you're seeing.

**Comment by twoerner** [comment]
I've added a bbappend to kirkstone which rewinds the version of U-Boot to v2021.01. Therefore you can build using kirkstone in all your layers and it should work.

Even with U-Boot rewound back to v2021.01, master additionally fails once the kernel starts (no further output). So that will need separate investigation (or a rewind on the kernel as well). The last working version of the kernel is kirkstone's linux-yocto_5.10 (5.10.149). kirkstone's linux-yocto_5.15 (5.15.72) doesn't work.

**Comment by pticon** [comment]
Hello,

I also had this issue with the latest version of kirkstone and I was able to solve with this patch:
```
--- a/arch/arm/dts/am335x-pocketbeagle.dts
+++ b/arch/arm/dts/am335x-pocketbeagle.dts
@@ -15,6 +15,7 @@
 
        chosen {
                stdout-path = &uart0;
+               tick-timer = &timer2;
        };
 
        leds {
```

It turned out that the device tree for pocketbeagle loaded by U-Boot lacked chosen/tick-timer definition. After adding the missing property and rebuilding u-boot the board booted successfully U-Boot.

**Comment by twoerner** [comment]
@pticon that's great, thank you!
Can you please submit this upstream?

**Comment by twoerner** [comment]
This has been fixed with commit https://github.com/e-ale/meta-pocketbeagle/commit/62ec42684cc1aee89299d5050ae28d97ac7c3530 and submitted to upstream U-Boot: https://patchwork.ozlabs.org/project/uboot/patch/20230830152553.15465-1-twoerner@gmail.com/
